server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip
    gzip on;
    gzip_types text/html text/css application/javascript;

    # =========================
    # API Proxy (IMPORTANT 🔥)
    # =========================
    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # =========================
    # Frontend (SPA)
    # =========================
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static files
    location ~* \.(css|js|png|jpg|ico)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}