services:

  backend:
    image: tusharyadaav/todo-backend:latest
    container_name: todo-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - todo-network

  frontend:
    image: tusharyadaav/todo-frontend:latest
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge